name: a

on:
  push

jobs:
  m:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        a:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
        - "11"
        b:
        - "a"
        - "b"
        - "c"
        - "d"
        - "e"
        - "f"
        - "g"
        - "h"
        - "i"
        - "j"
        - "k"
    steps:
      - run: echo "$X" > $X.txt
        env:
          X: ${{ matrix.a }}${{ matrix.b }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.a }}${{ matrix.b }}
          path: ${{ matrix.a }}${{ matrix.b }}.txt
